# Generated by Django 5.1.4 on 2024-12-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characteristics", "0003_alter_mycharacteristics_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySpecific",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "id_charact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characteristics.mycharacteristics",
                    ),
                ),
            ],
        ),
    ]
