# Generated by Django 5.1.4 on 2024-12-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0004_alter_mycharacteristics_id_cell'),
        ('specific', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myspecific',
            name='id_charact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_specific', to='characteristics.mycharacteristics'),
        ),
    ]
