# Generated by Django 5.1.4 on 2024-12-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_alter_mycharacteristics_id'),
        ('phone', '0003_myphone_id_specific_alter_myphone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycharacteristics',
            name='id_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_characteristics', to='phone.myphone'),
        ),
    ]
