# Generated by Django 5.1.4 on 2024-12-31 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphone',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='myphone',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/250'),
        ),
        migrations.AlterField(
            model_name='myphone',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='myphone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
