# Generated by Django 5.1.4 on 2024-12-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myphone",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
