# Generated by Django 5.1.4 on 2024-12-29 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_myphone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphone',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
