# Generated by Django 5.1.4 on 2025-01-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_myphone_characteristics_myphone_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDictCharacteristic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='myphone',
            name='image_url',
        ),
    ]
