# Generated by Django 5.1.4 on 2024-12-26 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0002_alter_myphone_id"),
        ("specific", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myphone",
            name="id_specific",
            field=models.ManyToManyField(to="specific.myspecific"),
        ),
        migrations.AlterField(
            model_name="myphone",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
