# Generated by Django 5.1.4 on 2025-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_mydictcharacteristic_remove_myphone_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFunction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
