# Generated by Django 5.1.4 on 2024-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_myphone_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphone',
            name='haracteristics',
            field=models.JSONField(default=dict),
        ),
    ]
