# Generated by Django 5.1.4 on 2025-01-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_myfunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphone',
            name='functions',
            field=models.JSONField(default=dict),
        ),
    ]
