# Generated by Django 5.1.4 on 2024-12-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_rename_haracteristics_myphone_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphone',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/250'),
        ),
    ]
